### ISSUE TITLE
Exemplo de Criação de Prescrição

### ISSUE THREAD

**Issue by heukirne** [noharm-ai/white-label-example#1]
Dae garotoo!! :fireworks: 
Comecei o endpoint para criar prescrição. Dá uma olhada [addPrescriptionNoAuth()](https://github.com/noharm-ai/backend/commit/25c461f6cdb11e043f04d3ce17dc42e982545652#diff-ed9253eeb45ae950765fd8b1bb3107332b2449429ef7e38980ae768739656036R87-R103)

Por enquanto ele só recebe o id do departamento e do paciente, pode passar qualquer coisa.
Inicialmente o cliente vai definir o número da prescrição também, depois vemos se isso faz sentido. :kissing_heart:

**Comment by marceloarocha** [comment]
Eae eae eae!!

Criação de prescrição funcionando! :+1:

**Comment by heukirne** [comment]
Que boniteza!!! :heart_eyes: :heart_eyes:
